language: scala
scala:
  - 2.11.11
  - 2.12.3
sudo: false

cache:
  directories:
    $HOME/.ivy2
    $INSTALL_DIR

git:
  depth: 10

sbt_args: -Dsbt.log.noformat=true

env:
  global:
    INSTALL_DIR=$TRAVIS_BUILD_DIR/install
    VERILATOR_ROOT=$INSTALL_DIR
    PATH=$PATH:$VERILATOR_ROOT/bin:$TRAVIS_BUILD_DIR/utils/bin

stages:
  - prepare cache
  - test

jobs:
  include:
    - stage: prepare cache
      script:
        - bash .install_verilator.sh
        - verilator --version
        - bash .install_yosys.sh
        - yosys -V
      scala:
        - 2.11.11
        - 2.12.3
    - stage: test
      script:
        - sbt clean assembly publish-local
        - bash .run_chisel_tests.sh
